const mentorTypes = {
    FETCH_MENTORS_REQUEST:"FETCH_MENTORS_REQUEST",
    FETCH_MENTORS_SUCCESS:"FETCH_MENTORS_SUCCESS",
    FETCH_MENTORS_FAIL:"FETCH_MENTORS_FAIL",
    
    FETCH_MENTOR_REQUEST:"FETCH_MENTOR_REQUEST",
    FETCH_MENTOR_SUCCESS:"FETCH_MENTOR_SUCCESS",
    FETCH_MENTOR_FAIL:"FETCH_MENTOR_FAIL",
    
    MENTOR_VERIFICATION_REQUEST:"MENTOR_VERIFICATION_REQUEST",
    MENTOR_VERIFICATION_SUCCESS:"MENTOR_VERIFICATION_SUCCESS",
    MENTOR_VERIFICATION_FAIL:"MENTOR_VERIFICATION_FAIL",
    
    DELETE_MENTOR_REQUEST : 'DELETE_MENTOR_REQUEST',
    DELETE_MENTOR_SUCCESS : 'DELETE_MENTOR_SUCCESS',
    DELETE_MENTOR_FAIL : 'DELETE_MENTOR_FAIL',
}

export default mentorTypes