const mentorTypes = {
    FETCH_MENTORS_REQUEST:"FETCH_MENTORS_REQUEST",
    SET_MENTORS:"SET_MENTORS",
    FETCH_MENTORS_FAIL:"FETCH_MENTORS_FAIL",
    
    FETCH_MENTOR_REQUEST:"FETCH_MENTOR_REQUEST",
    SET_MENTOR:"SET_MENTOR",
    FETCH_MENTOR_FAIL:"FETCH_MENTOR_FAIL",
}

export default mentorTypes