export const orderTypes={
    CREATE_ORDER_REQUEST:"CREATE_ORDER_REQUEST",
    CREATE_ORDER_SUCCESS:"CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL:"CREATE_ORDER_FAIL",
    ORDER_CREATE_RESET:"ORDER_CREATE_RESET",
    
    ORDER_DETAILS_REQUEST:"ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS:"ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAIL:"ORDER_DETAILS_FAIL"
    
}