const studentTypes = {
    FETCH_STUDENTS_REQUEST:"FETCH_STUDENTS_REQUEST",
    FETCH_STUDENTS_SUCCESS:"FETCH_STUDENTS_SUCCESS",
    FETCH_STUDENTS_FAIL:"FETCH_STUDENTS_FAIL",
    
    FETCH_STUDENT_REQUEST:"FETCH_STUDENT_REQUEST",
    FETCH_STUDENT_SUCCESS:"FETCH_STUDENT_SUCCESS",
    FETCH_STUDENT_FAIL:"FETCH_STUDENT_FAIL",
    
    DELETE_STUDENT_REQUEST : 'DELETE_STUDENT_REQUEST',
    DELETE_STUDENT_SUCCESS : 'DELETE_STUDENT_SUCCESS',
    DELETE_STUDENT_FAIL : 'DELETE_STUDENT_FAIL',
}

export default studentTypes