export const userTypes={
    USER_SIGNIN_REQUEST:"USER_SIGNIN_REQUEST",
    USER_SIGNIN_SUCCESS:"USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAIL:"USER_SIGNIN_FAIL",
    USER_SIGNIN_ERROR:"USER_SIGNIN_ERROR",
    USER_SIGNOUT_SUCCESS:"USER_SIGNOUT_SUCCESS",
    
    USER_SIGNUP_REQUEST:"USER_SIGNUP_REQUEST",
    USER_SIGNUP_VERIFICATION:"USER_SIGNUP_VERIFICATION",
    USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
    USER_SIGNUP_ERROR:"USER_SIGNUP_ERROR",
    USER_SIGNUP_FAIL:"USER_SIGNUP_FAIL",
    
    USER_EMAIL_VERIFICATION_REQUEST:"USER_EMAIL_VERIFICATION_REQUEST",
    USER_EMAIL_VERIFICATION_SUCCESS:"USER_EMAIL_VERIFICATION_SUCCESS",
    USER_EMAIL_VERIFICATION_ERROR:"USER_EMAIL_VERIFICATION_ERROR",
    USER_EMAIL_VERIFICATION_FAIL:"USER_EMAIL_VERIFICATION_FAIL",
    
    USER_DETAILS_REQUEST:"USER_DETAILS_REQUEST",
    USER_DETAILS_SUCCESS:"USER_DETAILS_SUCCESS",
    USER_DETAILS_FAIL:"USER_DETAILS_FAIL",
    
    USER_PROFILE_UPDATE_REQUEST:"USER_PROFILE_UPDATE_REQUEST",
    USER_PROFILE_UPDATE_SUCCESS:"USER_PROFILE_UPDATE_SUCCESS",
    USER_PROFILE_UPDATE_FAIL:"USER_PROFILE_UPDATE_FAIL",
    USER_PROFILE_UPDATE_RESET:"USER_PROFILE_UPDATE_RESET"

}