 const courseTypes = {
     FETCH_COURSES_REQUEST:"FETCH_COURSES_REQUEST",
     SET_COURSES:"SET_COURSES",
     FETCH_COURSES_FAIL:"FETCH_COURSES_FAIL",
     
     FETCH_COURSE_REQUEST:"FETCH_COURSE_REQUEST",
     SET_COURSE:"SET_COURSE",
     FETCH_COURSE_FAIL:"FETCH_COURSE_FAIL",
}
 
 export default courseTypes